version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    level: DEBUG
    formatter: standard
    class: logging.StreamHandler
loggers:
  root:
    level: DEBUG
    handlers: [console]
